### ISSUE TITLE
Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by jasperrooduijn** [cliffano/nestor#56]
I have used nestor for years with a lot of pleasure. Since a couple of weeks it stopped working. I keep getting this error: 'Cannot read property 'headers' of undefined'. 

Job jobname was triggered successfully
/usr/local/lib/node_modules/nestor/lib/cli/job.js:191
          var buildUrl = response.headers.location;
                                  ^

TypeError: Cannot read property 'headers' of undefined
    at cb (/usr/local/lib/node_modules/nestor/lib/cli/job.js:191:35)
    at /usr/local/lib/node_modules/nestor/node_modules/swaggy-jenkins/src/ApiClient.js:458:9
    at Request.callback (/usr/local/lib/node_modules/nestor/node_modules/superagent/lib/node/index.js:688:3)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/nestor/node_modules/superagent/lib/node/index.js:615:10)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)

**Comment by jasperrooduijn** [comment]
@cliffano Did you had any chance to look at this? Would be great if i could use nestor again. Thanks.
